### ISSUE TITLE
module 'torch.mps' has no attribute 'is_available'

### ISSUE THREAD

**Issue by Jasonhomme** [kijai/ComfyUI-ELLA-wrapper#12]
Error occurred when executing ella_model_loader:

module 'torch.mps' has no attribute 'is_available'

File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/custom_nodes/ComfyUI-ELLA-wrapper/nodes.py", line 215, in loadmodel
self.pipe.enable_model_cpu_offload()
File "/opt/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 985, in enable_model_cpu_offload
if hasattr(device_mod, "empty_cache") and device_mod.is_available():

**Comment by Jasonhomme** [comment]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
loading ELLA
loading text model
creating pipeline
pipeline created
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/custom_nodes/ComfyUI-ELLA-wrapper/nodes.py", line 215, in loadmodel
    self.pipe.enable_model_cpu_offload()
  File "/opt/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 985, in enable_model_cpu_offload
    if hasattr(device_mod, "empty_cache") and device_mod.is_available():
AttributeError: module 'torch.mps' has no attribute 'is_available'

Prompt executed in 1.48 seconds

**Comment by Jasonhomme** [comment]
when i use : Python3 main.py --fp32-text-enc  

happens   ---->

got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/jasonhomme/Desktop/SDwebui/comfyui/ComfyUI/custom_nodes/ComfyUI-ELLA-wrapper/nodes.py", line 306, in process
    images = pipe(
  File "/opt/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 897, in __call__
    prompt_embeds, negative_prompt_embeds = self.encode_prompt(
  File "/opt/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 401, in encode_prompt
    prompt_embeds = prompt_embeds.to(dtype=prompt_embeds_dtype, device=device)
  File "/opt/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Prompt executed in 0.12 seconds

**Comment by kijai** [comment]
Hey, I'm not sure if this can work on mps, regardless I recommend rather trying this for of the native comfyUI ELLA implementation: https://github.com/kijai/ComfyUI_ELLA
