### ISSUE TITLE
Issue: ImportError: Diffusers version too old. Please update to 0.26.0 minimum.

### ISSUE THREAD

**Issue by kongwonpanda** [kijai/ComfyUI-ELLA-wrapper#21]
[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.11.0
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i5-13600KF - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3060
[Crystools INFO] NVIDIA Driver: 560.81
Comfy-Easy-Use v1.2.2: Loaded
Traceback (most recent call last):
  File "O:\ComfyUI-aki\custom_nodes\ComfyUI-ELLA-wrapper\nodes.py", line 20, in <module>
    from diffusers.loaders.single_file_utils import (
ImportError: cannot import name 'create_vae_diffusers_config' from 'diffusers.loaders.single_file_utils' (O:\ComfyUI-aki\.ext\Lib\site-packages\diffusers\loaders\single_file_utils.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "O:\ComfyUI-aki\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "O:\ComfyUI-aki\custom_nodes\ComfyUI-ELLA-wrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "O:\ComfyUI-aki\custom_nodes\ComfyUI-ELLA-wrapper\nodes.py", line 28, in <module>
    raise ImportError("Diffusers version too old. Please update to 0.26.0 minimum.")
ImportError: Diffusers version too old. Please update to 0.26.0 minimum.

Cannot import O:\ComfyUI-aki\custom_nodes\ComfyUI-ELLA-wrapper module for custom nodes: Diffusers version too old. Please update to 0.26.0 minimum.
Total VRAM 12288 MB, total RAM 32604 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V4.83.2)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2539 [f1d6cef7] | Released on '2024-08-14'
[ComfyUI-Manager] default cache updated: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/model-list.json
[ReActor] - STATUS - Running v0.5.1-a6 in ComfyUI
[ComfyUI-Manager] default cache updated: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/extension-node-map.json
Torch version: 2.3.1+cu121

**Comment by kongwonpanda** [comment]
If anyone can give me some help, I need fix it. THANX so much.

**Comment by hiowenluke** [comment]
Tencent has released official Comfy ELLA nodes that should now be used instead of this:
https://github.com/TencentQQGYLab/ComfyUI-ELLA

**Comment by kongwonpanda** [comment]
Let me try, thank you~!
